conf/requirements.txt

This fixes the dependency version conflict which happens due to
bottle-utils-html and bottle-utils-common explicitly depending on a specific
version of python-dateutil which is different than the one required by
Librarian.
This fix should have no side-effects.

Updated bottle-utils-html to 0.3.7

---

librarian/app.py
setup.py

This PR adds a console command `librarian` to replace `python -m librarian.app` dance. Stuff from the `if __name__ == '__main__` block were all shoved into the `main()` func.

Added librarian console command

---

Makefile

This PR fixes #245, and issue where make target for stopping FSAL would spawn a new instance and stop that one instead of the old one.

Fix for failure to stop FSAL cleanly

---

docs/samples/librarian.ini

This patch cleans up the sample .ini so it doesn't have keys that aren't really useful or cause the deployment to break. See #246

Removed twitter-related and other obsolete keys

---

Makefile
docs/source/development.rst
docs/source/local_file_library.rst
docs/source/make_targets.rst
scripts/reindex.py

This patch adds a `reindex` make target which causes a running FSAL instance to commence reindexing. Matching documentation is also provided.

Add reindex make target and docs

---

librarian/commands/facets.py
librarian/data/manager.py

Use the same method for filtering both dirs and files so they are treated the same way, allowing it to drop out entries that have no corresponding metadata fetched from the database.
Previously two different methods were used, of which the one used for directories didn't ignore entries with missing metadata, causing an unhandled `KeyError` exception.

Fix content listing

---

librarian/views/filemanager/_main.tpl

Previously, the go up button disappeared when the current working directory is the root folder itself. This PR restored the previous behavior.

Fix go up button to disappear when cwd is root

---

librarian/dashboard/diskspace.py

Diskspace dashboard plugin failed to load because of a typo in the method name for getting consolidation status in the initial load of the dashboard plugin.

Fix typo in methodname of getting consolidate status

---

librarian/routes/ondd.py

This PR just fixes the names of the excluded plugin names on ONDD route handlers. They have been suffixed with the "_plugin" string, which was missing in the current definitions.

Fix excluded plugin names on ondd routes

---

librarian/core/contrib/assets/commands.py
librarian/core/pubsub.py

This fixes the `--assets` and `--collect` commands, running them after assets collectors have been installed.
An optional parameter `condition` is added to event subscription mechanism.
`condition` is a callable object which is passed the event & event parameters. 
It should return False if the subscriber is to skipped.

Fix asset commands to run after assets collector finished

---

librarian/plugins/captive.py
librarian/plugins/lock.py
librarian/plugins/timer.py

This PR just removes the wrapper function that was around the plugins as it was required in librarian 3.x for them to be installed, and assigns an explicit name to each of them.

Adapt plugins to make them usable by the collector api

---

librarian/views/ui/pager.tpl

Fixes a unicode error on Updates page because of missing quoting.

Fix unicode error on updates page due to missing url quoting

---

librarian/data/meta/links.py

Fixes the name of the database being access in `links` module (leftover from the transition to the unified librarian database)

Fix database name in links module

---

librarian/routes/setup.py
tests/routes/test_setup_routes.py

This PR fixes the broken unittest with the merge of the change to `NonIterableRouteBase` route bases.

Fix broken test after fixing setup diag route handler

---

librarian/views/filemanager/_audio.tpl
librarian/views/filemanager/_folder.tpl
librarian/views/filemanager/_image.tpl
librarian/views/filemanager/_playlist.tpl
librarian/views/filemanager/_video.tpl

This PR backports the fixes already applied in librarian-filemanager to librarian 4.0 so that all buttons and links are intercepted properly with accurate data.

Fix analytics

---

docs/source/developers/index.rst
docs/source/developers/setup_wizard.rst
librarian/setup/auth.py
librarian/setup/language.py
librarian/setup/ondd.py
librarian/views/setup/setup_base.tpl

This PR bumps existing setup wizard step indices & creates spaces in between for other components to interject themselves.
This also enables individual steps to enable multipart form encoding by setting `step_multipart` to True in their template context.

Setup wizard customizations

---

librarian/hooks.py

Register error handlers with our specific app instance, not allowing bottle to use default_app (I guess)
This behavior was already observed with hook as well, where registering hooks through the global bottle.hook function didn't trigger them, while registering them through `app_instance.hook` did.

Fix error handler route registration

---

librarian/data/tuner_presets.py
librarian/helpers/ondd.py

This commit factors tuner presets out of the helpers module such that it can be
updated separately.

Factor out tuner presets into separate module

---

librarian/data/meta/archive.py

Fixes the below shown error when searching for a path ending with a slash:
```
Traceback (most recent call last):
File "/usr/bin/bottle.py", line 922, in _cast
iout = iter(out)
File "/usr/lib/python2.7/site-packages/streamline/base.py", line 159, in __iter__
self.create_response()
File "/usr/lib/python2.7/site-packages/streamline/template.py", line 117, in create_response
super(XHRPartialRoute, self).create_response()
File "/usr/lib/python2.7/site-packages/streamline/template.py", line 92, in create_response
super(TemplateRoute, self).create_response()
File "/usr/lib/python2.7/site-packages/streamline/base.py", line 145, in create_response
self.body = meth(*self.args, **self.kwargs)
File "/usr/lib/python2.7/site-packages/librarian/routes/filemanager.py", line 121, in get
result = …
```

Fix search for paths that end with a slash and have a direct match

---

librarian/forms/ondd.py

The 'Custom' option in tuner presets field has a value of -1, but the form
validates it in the range between 0 and num presets. This means that selecting
custom results in validation failure. This patch fixes the validator to include
-1 for the custom option.

Account for custom option when validating presets

---

librarian/views/ui/forms.tpl

Some of the form-related defs like select, allow for useful extra keyword
arguments that are not directly passable through the field() def. This patch
modifies the field def to relay extra keyword arguments to other concrete field
defs. There is no special checking, so it is up to the devloper to ensure only
valid kwargs are used.

Allow extra kwargs for field() def

---

librarian/config.ini
librarian/core/contrib/system/config.ini
librarian/core/contrib/system/hooks.py

Add initialize hook to system component which sets the global tempdir location to the path specified in the config file

Set tempdir location through config

---

librarian/data/meta/processors.py
librarian/routes/filemanager.py
librarian/views/filemanager/_html.tpl
tests/data/meta/test_processors.py

Fix issue when html files are found in a folder but none of their filenames match one of the known html view entry points. For these cases pick the first filename by alphabetical order.

Fix html view auto-opener

---

librarian/config.ini
librarian/core/contrib/auth/users.py
librarian/forms/auth.py
librarian/setup/auth.py
librarian/utils/sysuser.py
librarian/views/setup/step_superuser.tpl

This commit introduces some code and a new setting that can cause the superuser
step to create a proper system account as well.
A new boolean configuration option, 'session.super_is_system' is introduced,
which causes the setup wizard step to take additional action when set to true.
The creation of a system user account is currently hard-wired to
/usr/sbin/adduser command (provided by Busybox on Outernet receivers), and is
not expected to work on systems that do not have a Busybox-compatible versions
of these commands. During account creation, an 'outernet' system account is
removed, which is also an assumption that holds true only on Outernet
receivers. Finally, the home directory of the new system account will always be
that of the removed 'outernet' users to simplify account creation.

Make superuser (possibly) double as system user

---

librarian/views/base.tpl

Since the menu was disabled when there is only 1 item, there had been ne way to
get back to the main page from any of the inner pages. This commit adds a link
to sys:root path from the OUTERNET logo when menu is disabled.
Fixes #363

Add link to system root from the Outernet logo

---

librarian/data/meta/processors.py

Add gif extension to the list of supported image formats. There was a reason for this list being strict as it looks, which I don't remember, but if needed,we can extend with additional formats for which we are sure they can work.

Enable gif format support in image processor

---

librarian/data/meta/processors.py
librarian/helpers/filemanager.py

This patch enables generating the correct icon and view (Read) for .htmlgz files.
.htmlgz files are .html files compressed with gzip. 
These files are required to support the wikipedia viewer app.
For correct operation, a related rule must also be added to the webserver (lighttpd) config, so that it adds the correct headers for .htmlgz

Add support for compressed html (.htmlgz) files

---

librarian/data/meta/processors.py

allows htmlgz files in subfolders to be viewed in the "read" tab.

Add "htmlgz" extension to htmlprocessor list

---

librarian/data/meta/processors.py

.html.gz is much easier for users to work with, when using desktop or outernet_in_a_box.

add .html.gz support

---

dependencies/requirements.txt
librarian/config.ini
librarian/core/collectors/tasks.py

process for each client. This caused the whole task scheduler to execute
tasks in parallel from all the processes (main and forks as well), which
lead to unforeseen errors during concurrent database access. The new
version of greentasks has a flag to disallow running from forks, and
this patch sets librarian up to use it.

The ftp component of librarian uses multiprocessing, forking the main

---

librarian/plugins/captive.py

Since the refactoring, captive portal templates have been moved into the captive subfolder, but the plugin was not adjusted to look for them in it,

Fix missin folder prefix for captive portal template paths
